# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyRightsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_made_public', models.DateField()),
                ('company_name', models.TextField()),
                ('location', models.CharField(max_length=30)),
                ('breach_type', models.CharField(choices=[('CARD', 'Payment Card Fraud'), ('HACK', 'Hacking or Matware attack'), ('INSD', 'Insider Breach Attack'), ('PHYS', 'Physical Loss'), ('PORT', 'Portable Device Breach'), ('STAT', 'Stationary Computer Loss'), ('DISC', 'Uninteded Disclosure'), ('Unknown', 'Uncertain Type of Breach')], max_length=8)),
                ('org_type', models.CharField(choices=[('BSF', 'BUsinesses-Financial and Insurance Services'), ('BSO', 'Businesses-Other'), ('BSR', 'Businesses-Retail/Merchant-Including Online Retail'), ('EDU', 'Educational Instituitions'), ('GOV', 'Government & Military'), ('MED', 'Healthcare, Medical Providers & Medical Insurance Services'), ('NGO', 'Nonprofits')], max_length=3)),
                ('numberOf_records_breaches', models.TextField()),
                ('total_records', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('info_source', models.CharField(max_length=30)),
            ],
        ),
    ]
